### ISSUE TITLE
[Feature Request]: Incremental construction of knowledge graph

### ISSUE THREAD

**Issue by c0derm4n** [microsoft/graphrag#1100] opened 2024-09-06 05:32 UTC
Does the current version support incremental construction of knowledge graphs?
当前版本是否支持增量构造知识图谱？
If there are changes in the corpus in the knowledge base, it is too wasteful to reconstruct the knowledge graph; If incremental construction of knowledge graphs is supported, it will be of great help for practical implementation
如果知识库中语料产生变化，需要重新构造知识图谱，过于浪费；如果支持增量构造知识图谱，对于实际落地会有很大帮助

**Comment by gusye1234** [comment] 2024-09-07 02:58
Hi, you can checkout this [repo](https://github.com/gusye1234/nano-graphrag/tree/main), it supports incremental insert for entities and relationships.

**Comment by natoverse** [comment] 2024-09-09 21:51
Duplicate of #741

**Closed by natoverse** 2024-09-09 21:51 UTC
Labels: enhancement

**Comment by c0derm4n** [comment] 2024-09-10 10:10
1
