### ISSUE TITLE
LLM Calls

### ISSUE THREAD

**Issue by riyajatar37003** [microsoft/graphrag#598] opened 2024-07-17 06:47 UTC
### Is your feature request related to a problem? Please describe.

Hi,
when we do the local or global search we get number of llm calls , is there any way we can get total number of llm calls made for each workflow/pipeline ?

Thanks

**Comment by natoverse** [comment] 2024-08-09 00:54
We are working on an injectable logger to help assess costs. In the meantime, here is a new article discussing GraphRAG costs: https://techcommunity.microsoft.com/t5/ai-azure-ai-services-blog/graphrag-costs-explained-what-you-need-to-know/ba-p/4207978

**Comment by natoverse** [comment] 2024-08-09 00:55
Closing this as a duplicate of #581

**Closed by natoverse** 2024-08-09 00:55 UTC
Labels: enhancement, backlog
