### ISSUE TITLE
[Issue]: <title> Examples Data File Missing 

### ISSUE THREAD

**Issue by xinzheng99** [microsoft/graphrag#989] opened 2024-08-21 03:15 UTC
### Do you need to file an issue?

- [x] I have searched the existing issues and this bug is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [X] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the issue

When I tried to learn the examples under the examples directory, I found that I didn't have the data I needed in the file.
Path: examples/entity_extraction/with_graph_intelligence/run.py
Need: `sample_data_dir = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "../../_sample_data/"
)

shared_dataset = asyncio.run(
    load_input(
        PipelineCSVInputConfig(
            file_pattern=".*\\.csv$",
            base_dir=sample_data_dir,
            source_column="author",
            text_column="message",
            timestamp_column="date(yyyyMMddHHmmss)",
            timestamp_format="%Y%m%d%H%M%S",
            title_column="message",
        ),
    )
)`

"../../_sample_data/" does not exist, and I 

### Steps to reproduce

Jus the file doesn't exist.

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version: latest
- Operating System:
- Python Version:
- Related Issues:

**Comment by xinzheng99** [comment] 2024-08-21 03:56
It came up when I randomly constructed the DATA:
`dataset = pd.DataFrame([
    {"author": "Eva", "message": "I'm fine, thanks!", "date(yyyyMMddHHmmss)": 20240821204422},
    {"author": "Eva", "message": "I'm fine, thanks!", "date(yyyyMMddHHmmss)": 20240821204422},
    {"author": "Eva", "message": "I'm fine, thanks!", "date(yyyyMMddHHmmss)": 20240821204422},
    {"author": "Eva", "message": "I'm fine, thanks!", "date(yyyyMMddHHmmss)": 20240821204422},
])
`
`Traceback (most recent call last):
  File "/Users/maxz/graphrag-source/examples/entity_extraction/with_nltk/run.py", line 93, in <module>
    asyncio.run(run_python())
  File "/opt/anaconda3/envs/graphrag-raw/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/graphrag-raw/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/graphrag-raw/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/maxz/graphrag-source/examples/entity_extraction/with_nltk/run.py", line 81, in run_python
    async for table in run_pipeline(dataset=dataset, workflows=workflows):
  File "/opt/anaconda3/envs/graphrag-raw/lib/python3.11/site-packages/graphrag/index/run.py", line 220, in run_pipeline
    loaded_workflows = load_workflows(
                       ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/graphrag-raw/lib/python3.11/site-packages/graphrag/index/workflows/load.py", line 75, in load_workflows
    workflow = create_workflow(
               ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/graphrag-raw/lib/python3.11/site-packages/graphrag/index/workflows/load.py", line 134, in create_workflow
    steps = steps or _get_steps_for_workflow(name, config, additional_workflows)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/graphrag-raw/lib/python3.11/site-packages/graphrag/index/workflows/load.py", line 163, in _get_steps_for_workflow
    raise UnknownWorkflowError(name)
graphrag.index.errors.UnknownWorkflowError: Unknown workflow: entity_extraction`

**Comment by natoverse** [comment] 2024-08-21 18:24
Marking as duplicate of https://github.com/microsoft/graphrag/issues/353

**Closed by natoverse** 2024-08-21 18:24 UTC
Labels: triage
