### ISSUE TITLE
[Bug]: <title>KeyError: 'covariate_type'

### ISSUE THREAD

**Issue by laocryhard** [microsoft/graphrag#1109] opened 2024-09-10 01:59 UTC
### Do you need to file an issue?

- [ ] I have searched the existing issues and this bug is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by natoverse** [comment] 2024-09-10 16:51
Duplicate of #1110

**Closed by natoverse** 2024-09-10 16:51 UTC
Labels: bug, triage

**Comment by laocryhard** [comment] 2024-09-26 07:33
> Duplicate of #1110
Sorry for not seeing your reply until now. Now the problem has been solved, just turn off the covariate. Currently, the graphrag function is not perfect
