### ISSUE TITLE
[Feature Request]: Adding an optional layer in order to de-duplicate entities whenever possible.

### ISSUE THREAD

**Issue by ruplisso** [microsoft/graphrag#1223] opened 2024-09-26 17:50 UTC
### Do you need to file an issue?

- [X] I have searched the existing issues and this feature is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [X] I believe this is a legitimate feature request, not just a question. If this is a question, please use the Discussions area.

### Is your feature request related to a problem? Please describe.

The current Entities extraction method  lead to a lot of duplicates on some documentation.

### Describe the solution you'd like

An additional step of consolidation could be useful in order to remove duplicate when confidence is high enough.

**Comment by natoverse** [comment] 2024-10-01 21:56
Duplicate of #113

**Closed by natoverse** 2024-10-01 21:56 UTC
Labels: enhancement
