### ISSUE TITLE
[Issue]: How to incorporate conversation history when running the query engine?

### ISSUE THREAD

**Issue by garfieldjin** [microsoft/graphrag#717] opened 2024-07-25 19:48 UTC
### Is there an existing issue for this?

- [ ] I have searched the existing issues
- [ ] I have checked [#657](https://github.com/microsoft/graphrag/issues/657) to validate if my issue is covered by community support

### Describe the issue

I followed instructions on https://microsoft.github.io/graphrag/posts/get_started/ and was able to run the query engine. I see in `settings.yaml`, we can set the parameter `conversation_history_max_turns` for `local_search` but when I run 
```
python -m graphrag.query \
--root ./ragtest \
--method local \
"Who is Scrooge, and what are his main relationships?"
```
and then
```
python -m graphrag.query \
--root ./ragtest \
--method local \
"Give me the answer again for my last question asked."
```
I got:
`SUCCESS: Local Search Response: Sure, I can provide a detailed response based on the data provided. However, I need to know what your last question was. Could you please repeat your question?
`
Why is it not able to access the conversation history? How can I enable that?

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by natoverse** [comment] 2024-07-25 22:27
Duplicate of #480

**Closed by natoverse** 2024-07-25 22:27 UTC
