### ISSUE TITLE
Azure AI Vector Store Batching Errors

### ISSUE THREAD

**Issue by darthtrevino** [microsoft/graphrag#232] opened 2024-05-16 16:43 UTC
reported by Kenneth Chen @ CELA; some batch uploads are failing on their end

Docs: https://learn.microsoft.com/en-us/azure/search/search-what-is-data-import - they may be running into the 16MB per batch limit

**Comment by AlonsoGuevara** [comment] 2024-07-06 02:35
Resolving this as it was caused by faulty configuration when overriding default values

**Closed by AlonsoGuevara** 2024-07-06 02:35 UTC
Labels: triage
